app = "coach-flow-app"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  TZ = "Pacific/Auckland"

[[services]]
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 40

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
